name: "Link to Projects with field"
description: "This Action allows you to tie issues and pull requests to Projects by specifying any value for any field"
inputs:
  GH_TOKEN:
    description: "GitHub Token(Required: repo, admin:org, projects)"
    required: true
  IsOrganization:
    description: "Is the repository in an organization"
    default: "false"
  ProjectsNumber:
    description: "The number of the project you want to link to"
    required: true
  FieldType:
    description: "Currently only Single Select is supported"
    default: "single_select"
  FiledKeyValues:
    description: "The key value pairs of the field and the value you want to link to"
    required: true
    default: '[{"key": "Status", "value": "Todo"}]'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Link Project
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        EVENT_NAME: ${{ github.event_name }}
        ISSUE_HTML_URL: ${{ github.event.issue.html_url }}
        PR_HTML_URL: ${{ github.event.pull_request.html_url }}
        OWNER: ${{ github.repository_owner }}
        PROJECT_NUM: ${{ inputs.ProjectsNumber }}
      run: |
        chmod +x ./src/link-project.sh
        ./src/link-project.sh

    - name: Get Global Id
      shell: bash
      run: |
        chmod +x ./src/get-global-id.sh
        ./src/get-global-id.sh
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        IS_ORG: ${{ inputs.IsOrganization }}
        OWNER: ${{ github.repository_owner }}
        PROJECT_NUM: ${{ inputs.ProjectsNumber }}
        FIELD_KEY_VALUES: ${{ inputs.FiledKeyValues }}

    - name: Get Item Id
      shell: bash
      run: |
        chmod +x ./src/get-item-id.sh
        ./src/get-item-id.sh
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        REPOSITORY: ${{ github.repository }}
        EVENT_NAME: ${{ github.event_name }}
        NUMBER: ${{ github.event.number }}
        OWNER: ${{ github.repository_owner }}

    - name: Set Fields
      shell: bash
      run: |
        chmod +x ./src/set-fields.sh
        ./src/set-fields.sh
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        FIELD_ID_VALUES: ${{ env.FIELD_ID_VALUES }}
        ITEM_ID: ${{ env.ITEM_ID }}
        PROJECT_ID: ${{ env.PROJECT_ID }}
